apiVersion: apps/v1
kind: Deployment
metadata:
  name: jav
  labels:
    app: jav
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jav
  template:
    metadata:
      labels:
        app: jav
    spec:
      containers:
      - name: jav
        image: akarolence/spring-splunk:30
        ports:
        - containerPort: 8084
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: akarolence/test-web:17
        ports:
        - containerPort: 4200



---
kind: Service
apiVersion: v1
metadata:
  name: jav
spec:
  selector:
    run: jav
  type: NodePort
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8084
    
---
kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  selector:
    run: web
  type: NodePort
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 4200


