apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: splunk
  name: kustomize-kustomize-nginx-ng4-service
  namespace: default
spec:
  ingressClassName: ngrok
  rules:
    - host: argocd-server-nKVA5vIK.ngrok.app
    - http:
        paths:
          - backend:
              service:
                name: kustomize-splunk
                port:
                  number: 8084
            path: /app
            pathType: Prefix
          - backend:
              service:
                name: kustomize-web
                port:
                  number: 4200
            path: /web
            pathType: Prefix
