apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxMC4xMi4xLjc1OjUwMDAiOiB7CgkJCSJhdXRoIjogImMyOW1kSFJsWTJnNmMyOW1kSFJsWTJnPSIKCQl9LAoJCSJkbXAuZG1lLnN5c3RlbXM6OTQ0MyI6IHsKCQkJImF1dGgiOiAiYzI5bWRIUmxZMmc2YzI5bWRIUmxZMmc9IgoJCX0sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHsKCQkJImF1dGgiOiAiWVdOb2FXRnliMnc2VUNGdU5HbG9PVVplUVRnckltMWwiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson


